### ISSUE TITLE
Elastizabbix causing high load on nodes.

### ISSUE THREAD

**Issue by hrzbrg** [mkhpalm/elastizabbix#1]
Hi,

we have a cluster of 5 nodes (master/data) and ~15 nodes (client only) to provide a cache for our product.
I put elastizabbix on one node and saw a huge increase in load. See the picture below.
<img width="458" alt="bildschirmfoto 2015-10-02 um 12 55 00" src="https://cloud.githubusercontent.com/assets/199414/10245150/3935b9a0-6905-11e5-90b0-4854b51e8b9a.png">

Are there any ways to avoid this? Something I could do in the Zabbix agent config?

**Comment by mkhpalm** [comment]
Do you have a lot of indexes? The current template has a doc count on every index under prototypes. I put that there sort of as an example in case anybody wanted to monitor indexes individually. It creates a lot of zabbix agent processing to iterate through a bunch of individual indexes from the json cache. 

Disable the inidex discovery or doc count item prototype under the zabbix template and it should resolve the issue you are seeing there. Another option is to put elastizabbix on one of the client nodes where its less sensitive to the load average. With the template I committed it will still alert if the nodes or cluster is experiencing issues. And thats really the crux of what I was trying to do here. To know when or why elastic is getting into a bad state before it becomes too late to do anything about it.

**Comment by hrzbrg** [comment]
Thanks for the explanation. Disabling the index discovery helped a lot.
