### ISSUE TITLE
Items flapping

### ISSUE THREAD

**Issue by weldpua2008** [mkhpalm/elastizabbix#10]
Hi,
There are many logentries about items become not supported in /var/log/zabbix/zabbix_server.log like this: 
`elastizabbix[nodes,nodes.VXoO3SGXsssss0NmHm0w.thread_pool.bulk.rejected]" became not supported: Received value [Traceback (most recent call last):  File "/usr/local/bin/elastizabbix", line 76, in <module>    stat = get_stat(api, stat)  File "/usr/local/bin/elastizabbix", line 44, in get_stat `
I think it's because update of cache is slow

**Comment by mkhpalm** [comment]
Thanks for the PR, merged
