### ISSUE TITLE
List support zabbix versions

### ISSUE THREAD

**Issue by tophercullen** [mkhpalm/elastizabbix#7]
I'm running zabbix 2.2.9 and ran into issues with the template as is. 
https://github.com/mkhpalm/elastizabbix/blob/master/template/templates_app_elasticsearch.xml#L1306

This filter stanza causes an error. 

There's also something incompatible with screen section. Graph prototype (type 20 in the template) is unavailable prior to 2.4

Removing  the filter stanza from both discovery rules and the few type 20 screen items allows for a successful import

I don't expect your template to support all version. It would be good to list the supported version of zabbix, or at least what version it was exported from

**Comment by mkhpalm** [comment]
Yeah, exported from 2.4 as you noticed. I added a little blurb about it in the readme.
